[package]
name = "skill_vesting"
version = "0.1.0"
description = "Vesting program for tokens based on social metrics"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "skill_vesting"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.29.0"
anchor-spl = "0.29.0"
solana-program = "1.17.0" 