import { PinataSDK } from "pinata";

const pinataJwt = process.env.NEXT_PUBLIC_PINATA_JWT;
const pinataGateway = process.env.NEXT_PUBLIC_PINATA_GATEWAY;

export const pinata = new PinataSDK({
    pinataJwt: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiJkZTE5MWQ0Ny1iOTUyLTRhNDEtODhlMS1jMGMwOWU5YThlNzkiLCJlbWFpbCI6ImFiaGlzaGVrc2luZ2gyMzU3NkBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwicGluX3BvbGljeSI6eyJyZWdpb25zIjpbeyJkZXNpcmVkUmVwbGljYXRpb25Db3VudCI6MSwiaWQiOiJGUkExIn0seyJkZXNpcmVkUmVwbGljYXRpb25Db3VudCI6MSwiaWQiOiJOWUMxIn1dLCJ2ZXJzaW9uIjoxfSwibWZhX2VuYWJsZWQiOmZhbHNlLCJzdGF0dXMiOiJBQ1RJVkUifSwiYXV0aGVudGljYXRpb25UeXBlIjoic2NvcGVkS2V5Iiwic2NvcGVkS2V5S2V5IjoiN2I2MGY0OGRmYjVmNGVlOTg0NDEiLCJzY29wZWRLZXlTZWNyZXQiOiJjYTgyOWQwZjdhN2EzNzAzZTI4ODk0ZGI1YWJhM2ViYzFjOGVlOWZjMzI4MmFhZWVhMWJjMDE3NTZmZmY0OTAyIiwiZXhwIjoxNzczNDc2OTcxfQ.bjCx5ciYW6pHcrM-ZCvbsEPnMZsFRG8PgUyt4wHXkOM',
    pinataGateway: "pink-practical-thrush-774.mypinata.cloud",
});