[features]
seeds = false
skip-lint = false

[programs.sonic]
greeting = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
token_factory = "SPLEZkhJTqLPgAB4wDUMTVnPTyCBTCUULYAjK6SxEKib"
skill_vesting = "SkLvStvncgAwXjKWnNVEF7MWZXkAF1MJ6Wkdynds8nqN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.sonic.game"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts" 